--- 
- name: my conditional playbooks
  hosts: all
  become: true


  tasks: 
   - name: install httpd packahe
     yum: 
       name: httpd
       state: installed
     when: ansible_os_family = "RedHat"

   - name: start httpd service
     service:
       name: httpd
       state: started
     when: ansible_os_family = "RedHat"


   - name: install apache2 service
     ansible.builtin.apt:
       name: apache2
       state: present
     when: ansible_os_family = "Debian"

  - name: start apache2 service
      service:
          name: 

