---
- hosts: all
  become: yes
  user: ansible
  connection: ssh


  tasks:
    - name: install multiple packages
      yum: name='{{item}}' state=installed
      with_items:
             - httpd
             - tree
             - java
             - docker

