---
- name: varibale playbook
  hosts: all
  become: true


  tasks:
    - name: creating a file with ansible playbook.
      file: path=/tmp/gouri.txt  state=touch
    

    - name: creating a file with ansible playbook.
      file: path=/tmp/gouri-dir  state=directory


    - name: copying a file
      copy: src=./ansible-file dest=/home/ansible    
