---
- hosts: all
  become: yes
  connection: ssh
  user: ansible


  vars:
    pkgname: httpd

  tasks:
    - name: installing httpd on webservers
      action: yum name='{{pkgname}}'
      state: installed
 
    
